package com.board.bdi.vo;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 게시판정보 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class BoardInfoVo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 게시판번호. */
	private Integer binum;

	/** 게시판제목. */
	private String bititle;

	/** 게시판내용. */
	private String bitext;

	/** 게시판파일. */
	private String bifile;

	/** 게시판날짜. */
	private String bicredat;

	/** 게시판수정일자. */
	private String bimodat;

	/** 게시판조회수. */
	private Integer bicnt;

	/** 게시판활성여부. */
	private Byte biactive;

	/** 유저정보. */
	private UserInfoVo userInfo;

	/** 댓글정보 목록. */
	private Set<CommentInfoVO> commentInfoSet;

	/**
	 * 생성자.
	 */
	public BoardInfoVo() {
		this.commentInfoSet = new HashSet<CommentInfoVO>();
	}

	/**
	 * 게시판번호을 설정합니다..
	 * 
	 * @param binum
	 *            게시판번호
	 */
	public void setBinum(Integer binum) {
		this.binum = binum;
	}

	/**
	 * 게시판번호을 가져옵니다..
	 * 
	 * @return 게시판번호
	 */
	public Integer getBinum() {
		return this.binum;
	}

	/**
	 * 게시판제목을 설정합니다..
	 * 
	 * @param bititle
	 *            게시판제목
	 */
	public void setBititle(String bititle) {
		this.bititle = bititle;
	}

	/**
	 * 게시판제목을 가져옵니다..
	 * 
	 * @return 게시판제목
	 */
	public String getBititle() {
		return this.bititle;
	}

	/**
	 * 게시판내용을 설정합니다..
	 * 
	 * @param bitext
	 *            게시판내용
	 */
	public void setBitext(String bitext) {
		this.bitext = bitext;
	}

	/**
	 * 게시판내용을 가져옵니다..
	 * 
	 * @return 게시판내용
	 */
	public String getBitext() {
		return this.bitext;
	}

	/**
	 * 게시판파일을 설정합니다..
	 * 
	 * @param bifile
	 *            게시판파일
	 */
	public void setBifile(String bifile) {
		this.bifile = bifile;
	}

	/**
	 * 게시판파일을 가져옵니다..
	 * 
	 * @return 게시판파일
	 */
	public String getBifile() {
		return this.bifile;
	}

	/**
	 * 게시판날짜을 설정합니다..
	 * 
	 * @param bicredat
	 *            게시판날짜
	 */
	public void setBicredat(String bicredat) {
		this.bicredat = bicredat;
	}

	/**
	 * 게시판날짜을 가져옵니다..
	 * 
	 * @return 게시판날짜
	 */
	public String getBicredat() {
		return this.bicredat;
	}

	/**
	 * 게시판수정일자을 설정합니다..
	 * 
	 * @param bimodat
	 *            게시판수정일자
	 */
	public void setBimodat(String bimodat) {
		this.bimodat = bimodat;
	}

	/**
	 * 게시판수정일자을 가져옵니다..
	 * 
	 * @return 게시판수정일자
	 */
	public String getBimodat() {
		return this.bimodat;
	}

	/**
	 * 게시판조회수을 설정합니다..
	 * 
	 * @param bicnt
	 *            게시판조회수
	 */
	public void setBicnt(Integer bicnt) {
		this.bicnt = bicnt;
	}

	/**
	 * 게시판조회수을 가져옵니다..
	 * 
	 * @return 게시판조회수
	 */
	public Integer getBicnt() {
		return this.bicnt;
	}

	/**
	 * 게시판활성여부을 설정합니다..
	 * 
	 * @param biactive
	 *            게시판활성여부
	 */
	public void setBiactive(Byte biactive) {
		this.biactive = biactive;
	}

	/**
	 * 게시판활성여부을 가져옵니다..
	 * 
	 * @return 게시판활성여부
	 */
	public Byte getBiactive() {
		return this.biactive;
	}

	/**
	 * 유저정보을 설정합니다..
	 * 
	 * @param userInfo
	 *            유저정보
	 */
	public void setUserInfo(UserInfoVo userInfo) {
		this.userInfo = userInfo;
	}

	/**
	 * 유저정보을 가져옵니다..
	 * 
	 * @return 유저정보
	 */
	public UserInfoVo getUserInfo() {
		return this.userInfo;
	}

	/**
	 * 댓글정보 목록을 설정합니다..
	 * 
	 * @param commentInfoSet
	 *            댓글정보 목록
	 */
	public void setCommentInfoSet(Set<CommentInfoVO> commentInfoSet) {
		this.commentInfoSet = commentInfoSet;
	}

	/**
	 * 댓글정보를 추가합니다..
	 * 
	 * @param commentInfo
	 *            댓글정보
	 */
	public void addCommentInfo(CommentInfoVO commentInfo) {
		this.commentInfoSet.add(commentInfo);
	}

	/**
	 * 댓글정보 목록을 가져옵니다..
	 * 
	 * @return 댓글정보 목록
	 */
	public Set<CommentInfoVO> getCommentInfoSet() {
		return this.commentInfoSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((binum == null) ? 0 : binum.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		BoardInfoVo other = (BoardInfoVo) obj;
		if (binum == null) {
			if (other.binum != null) {
				return false;
			}
		} else if (!binum.equals(other.binum)) {
			return false;
		}
		return true;
	}

}
